/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.WareHouse;

import Controller.ItemController;
import Model.CurrentUser;
import Model.Items;
import View.LoginView;
import View.MyMessageBox;

/**
 *
 * @author user
 */
public class ItemAdderView extends javax.swing.JPanel {

    /**
     * Creates new form ItemAdderView
     */
    LoginView parentFrame;
    public ItemAdderView(LoginView parentFramer) {
        initComponents();
        this.parentFrame= parentFramer;
        this.loadItemId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        itemIdTxtbx = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        itemNameTxtBx = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        unitPriceTxtBx = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        quantityTxtBx = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemDescTxtBx = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        vATTxtBx = new javax.swing.JTextField();
        addItemBtn = new javax.swing.JButton();
        homeMenuBut = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(72, 93, 215));
        jLabel2.setText("Add Items");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(49, 93, 23));
        jLabel7.setText("Item Id:");

        itemIdTxtbx.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(49, 93, 23));
        jLabel8.setText("Item Name:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(49, 93, 23));
        jLabel9.setText("Unit Price:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(49, 93, 23));
        jLabel10.setText("Quantity Available");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(49, 93, 23));
        jLabel11.setText("Item Description:");

        itemDescTxtBx.setColumns(20);
        itemDescTxtBx.setRows(5);
        jScrollPane1.setViewportView(itemDescTxtBx);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(49, 93, 23));
        jLabel12.setText("Value Added Tax:");

        addItemBtn.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        addItemBtn.setForeground(new java.awt.Color(0, 165, 250));
        addItemBtn.setText("Add Item");
        addItemBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addItemBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(186, 186, 186)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(97, 97, 97)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(59, 59, 59)
                                    .addComponent(itemNameTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(66, 66, 66)
                                    .addComponent(itemIdTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62)
                                        .addComponent(unitPriceTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(quantityTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(27, 27, 27)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(vATTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(addItemBtn)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemIdTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itemNameTxtBx)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(unitPriceTxtBx)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vATTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(addItemBtn)
                .addGap(22, 22, 22))
        );

        homeMenuBut.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        homeMenuBut.setForeground(new java.awt.Color(34, 112, 10));
        homeMenuBut.setText("Home");
        homeMenuBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMenuButMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(homeMenuBut)
                .addGap(58, 58, 58)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(homeMenuBut, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void homeMenuButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMenuButMouseClicked
        this.returnBack();
    }//GEN-LAST:event_homeMenuButMouseClicked

    private void addItemBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItemBtnMouseClicked
       this.addItem();
    }//GEN-LAST:event_addItemBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemBtn;
    private javax.swing.JButton homeMenuBut;
    private javax.swing.JTextArea itemDescTxtBx;
    private javax.swing.JTextField itemIdTxtbx;
    private javax.swing.JTextField itemNameTxtBx;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField quantityTxtBx;
    private javax.swing.JTextField unitPriceTxtBx;
    private javax.swing.JTextField vATTxtBx;
    // End of variables declaration//GEN-END:variables
    private boolean validateAllFields() {
        if ("".equals(this.itemIdTxtbx.getText().trim()) || this.itemDescTxtBx.getText().trim() == "" || this.itemNameTxtBx.getText().trim() == "" || this.unitPriceTxtBx.getText().trim() == "" || this.vATTxtBx.getText().trim() == "" || this.quantityTxtBx.getText().trim() == "") {
            MyMessageBox.displayMessage("All fields can't be left blank");
            return false;
        }
        try {
            int itemId = Integer.valueOf(itemIdTxtbx.getText().trim());
            int quantity = Integer.valueOf(quantityTxtBx.getText().trim());
            double vat = Double.valueOf(this.vATTxtBx.getText().trim());
            double price =Double.valueOf(this.unitPriceTxtBx.getText().trim());
        } catch (NumberFormatException ex) {
            MyMessageBox.displayMessage("Please make sure that the quantity,unit price, itemId and value added tax inputed in the right format");
            return false;
        }
        return true;
    }
    public void addItem(){
        if(validateAllFields()){
            Items itemToAdd= this.getItemBeingDisplayed();
            if(ItemController.createItem(itemToAdd)){
                MyMessageBox.displayMessage("Operation Successfull");
                returnBack();
                
            }else
            {
                MyMessageBox.displayMessage("Operation Unsuccessfull please contact the Admin");
            }
        }
    }
    private Items getItemBeingDisplayed(){
        Items myItem= new Items();
        myItem.setItemId(Integer.valueOf(itemIdTxtbx.getText().trim()));
        myItem.setItemName(this.itemNameTxtBx.getText().trim());
        myItem.setItemDescription(this.itemDescTxtBx.getText().trim());
        myItem.setQuantityAvailable(Integer.valueOf(quantityTxtBx.getText().trim()));
        myItem.setUnitPrice(this.unitPriceTxtBx.getText().trim());
        myItem.setValueAddedTax(Double.valueOf(this.unitPriceTxtBx.getText().trim()));
        return myItem;
    }
    public void returnBack(){
        WarehouseOptionView whov= new WarehouseOptionView(parentFrame);
        whov.setGreeting(CurrentUser.userFullName.trim());
        this.transitToHomePage(whov);
    }
    public void transitToHomePage(WarehouseOptionView whov){
       this.setVisible(false);
       parentFrame.remove(this);
       whov.setSize(978,570);
       parentFrame.add(whov);
       whov.setVisible(true);
       
   }
    private void loadItemId(){
        this.itemIdTxtbx.setText(String.valueOf(ItemController.getNextId()));
    }
}
