/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.WareHouse;

import Controller.ItemController;
import Model.CurrentUser;
import Model.Items;
import View.LoginView;
import View.MyMessageBox;
import java.util.LinkedList;

/**
 *
 * @author user
 */
public class LowestItemView extends javax.swing.JPanel {

    /**
     * Creates new form LowestItemView
     */
    LoginView parentFrame;
    LinkedList<Items> queriedList;
    int currentPointer;
    public LowestItemView(LoginView parentFramer) {
        initComponents();
        parentFrame= parentFramer;
        this.getAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        itemIdTxtBx = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        itemNameTxtBx = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        quantityTxtBx = new javax.swing.JTextField();
        prevBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        currentDispTxtBx = new javax.swing.JTextField();
        homeMenuBut = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 142, 27)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(72, 93, 215));
        jLabel2.setText("Items with lowest quantity");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(49, 93, 23));
        jLabel1.setText("Item Id:");

        itemIdTxtBx.setEditable(false);
        itemIdTxtBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(49, 93, 23));
        jLabel3.setText("Item Name:");

        itemNameTxtBx.setEditable(false);
        itemNameTxtBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(49, 93, 23));
        jLabel4.setText("Quantity Available:");

        quantityTxtBx.setEditable(false);
        quantityTxtBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quantityTxtBx.setForeground(new java.awt.Color(0, 102, 255));

        prevBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ccc(pnn).jpg"))); // NOI18N
        prevBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prevBtnMouseClicked(evt);
            }
        });

        nextBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ccc(n).jpg"))); // NOI18N
        nextBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextBtnMouseClicked(evt);
            }
        });

        currentDispTxtBx.setEditable(false);
        currentDispTxtBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentDispTxtBxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(prevBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(currentDispTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(110, 110, 110)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(itemIdTxtBx, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(itemNameTxtBx)
                            .addComponent(quantityTxtBx))))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemIdTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemNameTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(quantityTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nextBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prevBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(currentDispTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGap(43, 43, 43))
        );

        homeMenuBut.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        homeMenuBut.setForeground(new java.awt.Color(34, 112, 10));
        homeMenuBut.setText("Home");
        homeMenuBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMenuButMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(homeMenuBut, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(463, Short.MAX_VALUE)
                        .addComponent(homeMenuBut))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void currentDispTxtBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentDispTxtBxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentDispTxtBxActionPerformed

    private void homeMenuButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMenuButMouseClicked
       this.returnBack();
    }//GEN-LAST:event_homeMenuButMouseClicked

    private void prevBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevBtnMouseClicked
        this.prev();
    }//GEN-LAST:event_prevBtnMouseClicked

    private void nextBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBtnMouseClicked
        this.next();
    }//GEN-LAST:event_nextBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField currentDispTxtBx;
    private javax.swing.JButton homeMenuBut;
    private javax.swing.JTextField itemIdTxtBx;
    private javax.swing.JTextField itemNameTxtBx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton prevBtn;
    private javax.swing.JTextField quantityTxtBx;
    // End of variables declaration//GEN-END:variables
    public void returnBack(){
         WarehouseOptionView whov= new WarehouseOptionView(parentFrame);
       whov.setGreeting(CurrentUser.userFullName);
       this.transitToHomePage(whov);
    } 
    public void transitToHomePage(WarehouseOptionView whov){
       this.setVisible(false);
       parentFrame.remove(this);
       whov.setSize(978,570);
       parentFrame.add(whov);
       whov.setVisible(true);
       
   }
   public void getAllItems(){
       this.queriedList= ItemController.getItemsWithLowQuantity();
       System.out.println(this.queriedList.size());
       if(this.queriedList.size()<=0){
           MyMessageBox.displayMessage("All Items have sufficient quantity");
           this.returnBack();
       }else{
           displayCurrent();
       }
   }
   public void displayCurrent(){
       Items currentItem= this.queriedList.get(this.currentPointer);
       this.itemIdTxtBx.setText(String.valueOf(currentItem.getItemId()).trim());
       this.itemNameTxtBx.setText(currentItem.getItemName().trim());
       this.quantityTxtBx.setText(String.valueOf(currentItem.getQuantityAvailable()));
       this.currentDispTxtBx.setText((currentPointer+1)+"/"+this.queriedList.size());
       
   }
   public void next(){
       if(currentPointer>=this.queriedList.size()-1){
           currentPointer=0;
       }else{
           currentPointer+=1;
       }
       displayCurrent();
   }
   public void prev(){
       if(currentPointer<=0){
           currentPointer=0;
       }else
       {
           currentPointer-=1;
       }
       displayCurrent();
   }
}
