/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.WareHouse;

import Controller.ItemController;
import Model.CurrentUser;
import Model.Items;
import View.LoginView;
import View.MyMessageBox;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class SearchItemView extends javax.swing.JPanel {

    /**
     * Creates new form SearchItemView
     */
    Items searchResult;
    LoginView parentFrame;
    public SearchItemView(LoginView parentFramer) {
        initComponents();
        parentFrame=parentFramer;
        //this.itemIdTxt.setVisible(false);
        this.errorMsg.setVisible(false);
        this.disableUserButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchTxtBx = new javax.swing.JTextField();
        errorMsg = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        editItemBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        itemIdTxt = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(72, 93, 215));
        jLabel1.setText("Search by Item Id");

        errorMsg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        errorMsg.setForeground(new java.awt.Color(204, 0, 0));
        errorMsg.setText("Item Id does not exist");

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ccc(s1).jpg"))); // NOI18N
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });

        editItemBtn.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        editItemBtn.setForeground(new java.awt.Color(0, 165, 250));
        editItemBtn.setText("Edit Item");
        editItemBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editItemBtnMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Results for Item ID:");

        itemIdTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemIdTxt.setForeground(new java.awt.Color(0, 102, 102));
        itemIdTxt.setText("itemId");

        homeBtn.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(65, 104, 197));
        homeBtn.setText("Home");
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(searchTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(errorMsg))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(itemIdTxt))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchBtn)
                                    .addComponent(editItemBtn))))))
                .addGap(141, 141, 141))
            .addGroup(layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorMsg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBtn)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(itemIdTxt))
                .addGap(42, 42, 42)
                .addComponent(editItemBtn)
                .addGap(8, 8, 8)
                .addComponent(homeBtn)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents
    int itemId=0;
    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        
        try{
            itemId= Integer.valueOf(this.searchTxtBx.getText().trim());
        }catch(NumberFormatException ex){
            MyMessageBox.displayMessage("Please Enter a Number as the sales Id");
        }
        this.search(itemId);
    }//GEN-LAST:event_searchBtnMouseClicked

    private void editItemBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editItemBtnMouseClicked
       this.transitToEditPage(new EditItemView(parentFrame,this.searchResult));
    }//GEN-LAST:event_editItemBtnMouseClicked

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        this.returnBack();
    }//GEN-LAST:event_homeBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editItemBtn;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel itemIdTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxtBx;
    // End of variables declaration//GEN-END:variables
   public void search(int itemId){
        this.searchResult= ItemController.getItem(itemId);
        if(searchResult==null){
            this.disableUserButtons();
            this.errorMsg.setVisible(true);
            this.itemIdTxt.setText("");
        }else{
            this.enableUserButtons();
            this.errorMsg.setVisible(false);
            this.itemIdTxt.setText(String.valueOf(this.searchResult.getItemId()));
        }
       
    }
   public void disableUserButtons(){
       this.editItemBtn.setEnabled(false);
       //this.delItemBtn.setEnabled(false);
   }
   public void enableUserButtons(){
       this.editItemBtn.setEnabled(true);
       //this.delItemBtn.setEnabled(true);
        System.out.println(itemId);
   }
    private void returnBack() {
        WarehouseOptionView whov = new WarehouseOptionView(parentFrame);
        whov.setGreeting(CurrentUser.userFullName.trim());
        this.transitToHomePage(whov);
    }

    public void transitToHomePage(WarehouseOptionView sov) {
        this.setVisible(false);
        parentFrame.remove(this);
        sov.setSize(978, 570);
        parentFrame.add(sov);
        sov.setVisible(true);

    }
    public void delete(){
        int result=JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this item");
        if(result==JOptionPane.OK_OPTION){
            if(ItemController.delete(itemId)){
                MyMessageBox.displayMessage("Item successfully deleted");
            }else{
                MyMessageBox.displayMessage("Operation unsuccessful");
            }
        }else if(result==JOptionPane.CANCEL_OPTION){
            
        }
            
    }
    public void transitToEditPage(EditItemView eiv){
        this.setVisible(false);
        parentFrame.remove(this);
        eiv.setSize(978, 570);
        parentFrame.add(eiv);
        eiv.setVisible(true);
    }
}
