/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Controller;
import Model.Sales;
/**
 *
 * @author user
 */
public class SalesController {
    
    public static int getAutoGeneratedSalesId()
    {
        return Sales.getNextSalesId();
    }
    public static boolean storeSales(Sales salesToStore){
        if(salesToStore==null){
            return false;
        }
        return Sales.insert(salesToStore);
    }
    public static Sales getSales(int salesId){
        Sales result= Sales.retrieve(salesId);
        return result;
    }
}
