/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controller.*;
import Model.CurrentUser;
import Model.NumeruoUser;
import View.Manager.ManagerOptionView;
import View.SalesView.SalesOptionView;
import View.WareHouse.WarehouseOptionView;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class LoginView extends javax.swing.JFrame {

    
    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
       this.setResizable(false);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        loginLayoutPanel = new javax.swing.JPanel();
        loginPannel = new javax.swing.JPanel();
        loginImage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        uNameTxtBx = new javax.swing.JTextField();
        deptCombobx = new javax.swing.JComboBox();
        uPasswdtxtbx = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Numero Uno");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bs.jpg"))); // NOI18N

        loginLayoutPanel.setBackground(new java.awt.Color(255, 255, 255));

        loginPannel.setBackground(new java.awt.Color(255, 255, 255));
        loginPannel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 213, 6), 1, true));

        loginImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acct.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(20, 148, 23));
        jLabel3.setText("User Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(20, 148, 23));
        jLabel4.setText("Password:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(20, 148, 23));
        jLabel5.setText("Department:");

        uNameTxtBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uNameTxtBx.setForeground(new java.awt.Color(234, 142, 15));
        uNameTxtBx.setCaretColor(new java.awt.Color(102, 102, 0));

        deptCombobx.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        deptCombobx.setForeground(new java.awt.Color(238, 138, 10));
        deptCombobx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sales Department", "WareHouse Department", "Managerial Department" }));

        uPasswdtxtbx.setForeground(new java.awt.Color(255, 148, 20));
        uPasswdtxtbx.setText("jPasswordField1");

        jLabel6.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(27, 175, 253));
        jLabel6.setText("Please Login");

        loginButton.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        loginButton.setForeground(new java.awt.Color(0, 165, 250));
        loginButton.setText("Login");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginPannelLayout = new javax.swing.GroupLayout(loginPannel);
        loginPannel.setLayout(loginPannelLayout);
        loginPannelLayout.setHorizontalGroup(
            loginPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPannelLayout.createSequentialGroup()
                .addGroup(loginPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPannelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(loginImage)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(loginPannelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(loginPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPannelLayout.createSequentialGroup()
                                .addGroup(loginPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(loginPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deptCombobx, 0, 241, Short.MAX_VALUE)
                                    .addComponent(uPasswdtxtbx)))
                            .addGroup(loginPannelLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(uNameTxtBx)))))
                .addGap(134, 134, 134))
            .addGroup(loginPannelLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(loginButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginPannelLayout.setVerticalGroup(
            loginPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPannelLayout.createSequentialGroup()
                .addGroup(loginPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPannelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPannelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loginImage, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uNameTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(loginPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uPasswdtxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(loginPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deptCombobx, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(loginButton)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout loginLayoutPanelLayout = new javax.swing.GroupLayout(loginLayoutPanel);
        loginLayoutPanel.setLayout(loginLayoutPanelLayout);
        loginLayoutPanelLayout.setHorizontalGroup(
            loginLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayoutPanelLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(loginPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        loginLayoutPanelLayout.setVerticalGroup(
            loginLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayoutPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(loginPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bs.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(loginLayoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginLayoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        NumeruoUser user= new NumeruoUser();
        user.setUserName(this.uNameTxtBx.getText().trim());
        user.setUserPassword(String.valueOf(this.uPasswdtxtbx.getPassword()).trim());
        user.setUserDepartment(String.valueOf(this.deptCombobx.getSelectedItem()));
        System.out.println(user.getUserDepartment());

        if (LoginController.login(user)) {
            if (CurrentUser.userDepartment.equalsIgnoreCase("Warehouse Department")) {
                WarehouseOptionView warehousePanel = new WarehouseOptionView(this);
                warehousePanel.setGreeting(CurrentUser.userFullName);
                this.transitToWareHouseOptionWindow(warehousePanel);
            } else if (CurrentUser.userDepartment.equalsIgnoreCase("Managerial Department")) {
                ManagerOptionView managerOptionView= new ManagerOptionView(this);
                managerOptionView.setGreeting(CurrentUser.userFullName);
                this.transitToManagerOptionWindow(managerOptionView);
            } else {
                //MyMessageBox.displayMessage("Access Granted");
                SalesOptionView salesPanel = new SalesOptionView(this);
                salesPanel.setGreeting(CurrentUser.userFullName.trim());

                this.transitToOptionWindow(salesPanel);
            }
        } else {
            MyMessageBox.displayMessage("Sorry incorrect username, password or Department ");
        }
    }//GEN-LAST:event_loginButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox deptCombobx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginImage;
    private javax.swing.JPanel loginLayoutPanel;
    private javax.swing.JPanel loginPannel;
    private javax.swing.JTextField uNameTxtBx;
    private javax.swing.JPasswordField uPasswdtxtbx;
    // End of variables declaration//GEN-END:variables
    public void transitToOptionWindow(SalesOptionView myPannel){
       
        loginLayoutPanel.setVisible(false);
        this.remove(loginLayoutPanel);
        myPannel.setSize(978, 570);
        this.add(myPannel);
        myPannel.setVisible(true);
        
               
    }
    public void transitToWareHouseOptionWindow(WarehouseOptionView myPannel){
        loginLayoutPanel.setVisible(false);
        this.remove(loginLayoutPanel);
        //this.remove(optionMenuPanel);
       
        myPannel.setSize(1800,1000);
        this.add(myPannel);
        myPannel.setVisible(true);
        
        
    }
    public void setMenuSize(int width, int height){
        //this.optionMenuPanel.setSize(width,height);
    }
    public void transitToManagerOptionWindow(ManagerOptionView mov){
        loginLayoutPanel.setVisible(false);
        this.remove(loginLayoutPanel);
        mov.setSize(978,570);
        this.add(mov);
        mov.setVisible(true);
        
    }
}
