/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.Manager;

import Controller.LoginController;
import View.IGreetable;
import View.IHoverable;
import View.LoginView;
import View.PasswordChanger;
import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author user
 */
public class ManagerOptionView extends javax.swing.JPanel implements IGreetable,IHoverable {

    /**
     * Creates new form ManagerOptionView
     */
    LoginView parentFrame;
    public ManagerOptionView(LoginView parentFramer) {
        initComponents();
        parentFrame= parentFramer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addUsrBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        editUsrBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        viewAllUsersBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        changePasswdBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        logOutBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(37, 154, 205));
        welcomeLabel.setText("welcome");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        addUsrBtn.setBackground(new java.awt.Color(183, 239, 240));
        addUsrBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Userimages.jpg"))); // NOI18N
        addUsrBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUsrBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addUsrBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addUsrBtnMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(37, 154, 205));
        jLabel1.setText("Add User Account");

        editUsrBtn.setBackground(new java.awt.Color(183, 239, 240));
        editUsrBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imagesedit.jpg"))); // NOI18N
        editUsrBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editUsrBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editUsrBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editUsrBtnMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 154, 205));
        jLabel2.setText("Edit User Account");

        viewAllUsersBtn.setBackground(new java.awt.Color(183, 239, 240));
        viewAllUsersBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/678092-sign-add-128.png"))); // NOI18N
        viewAllUsersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAllUsersBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewAllUsersBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewAllUsersBtnMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(37, 154, 205));
        jLabel3.setText("View All Users");

        changePasswdBtn.setBackground(new java.awt.Color(183, 239, 240));
        changePasswdBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/secrecy-icon.png"))); // NOI18N
        changePasswdBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePasswdBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changePasswdBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changePasswdBtnMouseExited(evt);
            }
        });
        changePasswdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswdBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(37, 154, 205));
        jLabel6.setText("Change Password");

        logOutBtn.setBackground(new java.awt.Color(183, 239, 240));
        logOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image logou.jpg"))); // NOI18N
        logOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutBtnMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(37, 154, 205));
        jLabel4.setText("Log Out");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(addUsrBtn))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editUsrBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewAllUsersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(changePasswdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel6)))
                .addGap(26, 26, 26)
                .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logOutBtn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addUsrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editUsrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewAllUsersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changePasswdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logOutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseClicked
       this.logOut();
    }//GEN-LAST:event_logOutBtnMouseClicked

    private void addUsrBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUsrBtnMouseEntered
       this.enter(this.addUsrBtn);
    }//GEN-LAST:event_addUsrBtnMouseEntered

    private void addUsrBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUsrBtnMouseExited
      this.exit(this.addUsrBtn);
    }//GEN-LAST:event_addUsrBtnMouseExited

    private void editUsrBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editUsrBtnMouseEntered
       this.enter(this.editUsrBtn);
    }//GEN-LAST:event_editUsrBtnMouseEntered

    private void editUsrBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editUsrBtnMouseExited
       this.exit(this.editUsrBtn);
    }//GEN-LAST:event_editUsrBtnMouseExited

    private void logOutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseEntered
         this.enter(logOutBtn);
    }//GEN-LAST:event_logOutBtnMouseEntered

    private void logOutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseExited
        this.exit(logOutBtn);
    }//GEN-LAST:event_logOutBtnMouseExited

    private void addUsrBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUsrBtnMouseClicked
        this.transitToAddUserView(new UserAdderView(this.parentFrame));
    }//GEN-LAST:event_addUsrBtnMouseClicked

    private void viewAllUsersBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllUsersBtnMouseEntered
         this.enter(this.viewAllUsersBtn);
    }//GEN-LAST:event_viewAllUsersBtnMouseEntered

    private void viewAllUsersBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllUsersBtnMouseExited
        this.exit(this.viewAllUsersBtn);
    }//GEN-LAST:event_viewAllUsersBtnMouseExited

    private void changePasswdBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswdBtnMouseEntered
       this.enter(this.changePasswdBtn);
    }//GEN-LAST:event_changePasswdBtnMouseEntered

    private void changePasswdBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswdBtnMouseExited
       this.exit(this.changePasswdBtn);
    }//GEN-LAST:event_changePasswdBtnMouseExited

    private void editUsrBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editUsrBtnMouseClicked
       this.transitToUserEditorView(new UserEditorView(parentFrame));
    }//GEN-LAST:event_editUsrBtnMouseClicked

    private void viewAllUsersBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllUsersBtnMouseClicked
        this.transitToUserViewer(new UserViewer(parentFrame));
    }//GEN-LAST:event_viewAllUsersBtnMouseClicked

    private void changePasswdBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswdBtnMouseClicked
       this.transitToChangPasswordView(new PasswordChanger(parentFrame));
    }//GEN-LAST:event_changePasswdBtnMouseClicked

    private void changePasswdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswdBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changePasswdBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUsrBtn;
    private javax.swing.JButton changePasswdBtn;
    private javax.swing.JButton editUsrBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton viewAllUsersBtn;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
    

    @Override
    public void setGreeting(String userToGreet) {
        this.welcomeLabel.setText("Welcome "+ userToGreet);
    }
    
    public void logOut(){
        LoginView myView= new LoginView();
        this.setVisible(false);
        parentFrame.setVisible(false);
        myView.setVisible(true);
        myView.setLocationRelativeTo(null);
        LoginController.logOut();
    }
    public void transitToAddUserView(UserAdderView uav){
        this.setVisible(false);
       parentFrame.remove(this);
       uav.setSize(978,570);
       parentFrame.add(uav);
       uav.setVisible(true);
    }
    public void transitToUserEditorView(UserEditorView uev) {
        this.setVisible(false);
        parentFrame.remove(this);
        uev.setSize(978, 570);
        parentFrame.add(uev);
        uev.setVisible(true);
    }
    public void transitToUserViewer(UserViewer uver){
        this.setVisible(false);
        parentFrame.remove(this);
        uver.setSize(978, 570);
        parentFrame.add(uver);
        uver.setVisible(true);
    }
    public void transitToChangPasswordView(PasswordChanger pChange) {
        this.setVisible(false);
        parentFrame.remove(this);
        pChange.setSize(978, 570);
        parentFrame.add(pChange);
        pChange.setVisible(true);
    }
    @Override
    public void enter(JButton button) {
        button.setBackground(Color.orange);
        button.setSize((button.getWidth() + 15), (button.getHeight() + 15));
    }

    @Override
    public void exit(JButton button) {
        button.setBackground(new java.awt.Color(183, 239, 240));
        button.setSize((button.getWidth() - 15), (button.getHeight() - 15));
    }
}
