/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.SalesView;

import Controller.*;
import Model.Clients;
import Model.CurrentUser;
import View.LoginView;
import View.MyMessageBox;
import java.util.LinkedList;

/**
 *
 * @author user
 */
public class CreateClientView extends javax.swing.JPanel {
    private  LoginView parentFrame;

    /**
     * Creates new form createClient
     * @param parentFrame
     */
    public CreateClientView(LoginView parentFrame) {
        initComponents();
        this.parentFrame = parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        clientUserNameTxtbx = new javax.swing.JFormattedTextField();
        clientFullNameTxtbx = new javax.swing.JFormattedTextField();
        clientPhoneTxtbx = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientAddressTxtarea = new javax.swing.JTextArea();
        homeMenuBut = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(72, 93, 215));
        jLabel2.setText("Client Creator");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 109, 38), 1, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(49, 93, 23));
        jLabel1.setText("Client UserName:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(49, 93, 23));
        jLabel3.setText("Client Full Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(49, 93, 23));
        jLabel4.setText("Client Phone Number:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(49, 93, 23));
        jLabel5.setText("Client Address:");

        createButton.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        createButton.setForeground(new java.awt.Color(0, 165, 250));
        createButton.setText("Create");
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonMouseClicked(evt);
            }
        });

        clientAddressTxtarea.setColumns(20);
        clientAddressTxtarea.setRows(5);
        jScrollPane1.setViewportView(clientAddressTxtarea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clientPhoneTxtbx)
                    .addComponent(clientFullNameTxtbx)
                    .addComponent(clientUserNameTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(createButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(clientUserNameTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(clientFullNameTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(clientPhoneTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        homeMenuBut.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        homeMenuBut.setForeground(new java.awt.Color(34, 112, 10));
        homeMenuBut.setText("Home");
        homeMenuBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMenuButMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(homeMenuBut)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(homeMenuBut, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseClicked
        if(this.validateUserInput())
        {
            if(this.validateSqlInjection()==false){
                MyMessageBox.displayMessage("Please all fields can not contain special characters such as '*','=','/' and '\\'");
            }else
            {
                Clients clientToCreate= new Clients();
                clientToCreate.setUserName(this.clientUserNameTxtbx.getText().trim());
                clientToCreate.setClientName(this.clientFullNameTxtbx.getText().trim());
                clientToCreate.setClientAddress(this.clientAddressTxtarea.getText().trim());
                clientToCreate.setClientPhone(this.clientPhoneTxtbx.getText().trim());
                if(ClientController.createClient(clientToCreate)){
                    MyMessageBox.displayMessage("Client Successfully Created");
                }else
                {
                    MyMessageBox.displayMessage("Operation Unsuccessfull. Please check your data or call the Admin");
                }
            }
            
        }
    }//GEN-LAST:event_createButtonMouseClicked

    private void homeMenuButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMenuButMouseClicked
            SalesOptionView salesPanel= new SalesOptionView(parentFrame);
           salesPanel.setGreeting(CurrentUser.userFullName.trim());
           this.transitToHomePage(salesPanel);
    }//GEN-LAST:event_homeMenuButMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea clientAddressTxtarea;
    private javax.swing.JFormattedTextField clientFullNameTxtbx;
    private javax.swing.JFormattedTextField clientPhoneTxtbx;
    private javax.swing.JFormattedTextField clientUserNameTxtbx;
    private javax.swing.JButton createButton;
    private javax.swing.JButton homeMenuBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private boolean validateUserInput(){
        if(this.clientUserNameTxtbx.getText().trim().length()>50){
            MyMessageBox.displayMessage("The user name for the client can't be more than 50 characters");
            this.clientUserNameTxtbx.requestFocusInWindow();
            return false;
        }
        if(this.clientUserNameTxtbx.getText().trim().length()<=0){
            MyMessageBox.displayMessage("Please Input a client User Name");
            this.clientUserNameTxtbx.requestFocusInWindow();
            return false;
        }
        if(this.clientFullNameTxtbx.getText().trim().length()>150){
            MyMessageBox.displayMessage("The client's full name can't be more than 150 characters");
            this.clientFullNameTxtbx.requestFocusInWindow();
            return false;
        }
        if (this.clientFullNameTxtbx.getText().trim().length() <= 0) {
            MyMessageBox.displayMessage("Please Input a Full Name for the Client");
            this.clientFullNameTxtbx.requestFocusInWindow();
            return false;
        }
        if(this.clientPhoneTxtbx.getText().trim().length()>30){
            MyMessageBox.displayMessage("Client Phone Number can't exceed 30 characters");
            this.clientPhoneTxtbx.requestFocusInWindow();
            return false;
        }
         if(this.clientPhoneTxtbx.getText().trim().length()<=0){
            MyMessageBox.displayMessage("Please Input the Client phone Number");
            this.clientPhoneTxtbx.requestFocusInWindow();
            return false;
        }
          if(this.clientAddressTxtarea.getText().trim().length()<=0){
            MyMessageBox.displayMessage("Please input Client's Address");
            this.clientAddressTxtarea.requestFocusInWindow();
            return false;
        }
           if(this.clientAddressTxtarea.getText().trim().length()>200){
            MyMessageBox.displayMessage("Client Address can't exceed 200 characters");
            this.clientAddressTxtarea.requestFocusInWindow();
            return false;
        }
           return true;
    }
   public boolean validateSqlInjection(){
         LinkedList<String> userFields= new LinkedList<>();
        userFields.add(this.clientUserNameTxtbx.getText().trim());
        userFields.add(this.clientFullNameTxtbx.getText().trim());
        userFields.add(this.clientAddressTxtarea.getText().trim());
        userFields.add(this.clientPhoneTxtbx.getText().trim());
        return Validator.validate(userFields);
   }
   public void transitToHomePage(SalesOptionView sov){
       this.setVisible(false);
       parentFrame.remove(this);
       sov.setSize(978,570);
       parentFrame.add(sov);
       sov.setVisible(true);
       
   }

}
