/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.SalesView;

import Controller.ClientController;
import Model.Clients;
import Model.CurrentUser;
import View.LoginView;
import View.MyMessageBox;

/**
 *
 * @author user
 */
public class EditClientView extends javax.swing.JPanel {

    /**
     * Creates new form EditClientView
     */
    Clients clientToEdit;
    String clientUserName;
    LoginView parentFrame;
    public EditClientView(LoginView parentFramer) {
        initComponents();
       this.parentFrame= parentFramer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        saveChangeBtn = new javax.swing.JButton();
        clientUserNameTxtbx = new javax.swing.JFormattedTextField();
        clientFullNameTxtbx = new javax.swing.JFormattedTextField();
        clientPhoneTxtbx = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientAddressTxtarea = new javax.swing.JTextArea();
        searchBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(72, 93, 215));
        jLabel2.setText("Client Editor");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 109, 38), 1, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(49, 93, 23));
        jLabel1.setText("Client UserName:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(49, 93, 23));
        jLabel3.setText("Client Full Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(49, 93, 23));
        jLabel4.setText("Client Phone Number:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(49, 93, 23));
        jLabel5.setText("Client Address:");

        saveChangeBtn.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        saveChangeBtn.setForeground(new java.awt.Color(0, 165, 250));
        saveChangeBtn.setText("Save Changes");
        saveChangeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveChangeBtnMouseClicked(evt);
            }
        });

        clientFullNameTxtbx.setEditable(false);

        clientPhoneTxtbx.setEditable(false);

        clientAddressTxtarea.setEditable(false);
        clientAddressTxtarea.setColumns(20);
        clientAddressTxtarea.setRows(5);
        jScrollPane1.setViewportView(clientAddressTxtarea);

        searchBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(0, 165, 250));
        searchBtn.setText("Search");
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(clientPhoneTxtbx)
                                .addComponent(clientFullNameTxtbx)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(clientUserNameTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(saveChangeBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(clientUserNameTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(clientFullNameTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(clientPhoneTxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveChangeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );

        homeBtn.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(34, 112, 10));
        homeBtn.setText("Home");
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveChangeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveChangeBtnMouseClicked
        this.saveChanges();
    }//GEN-LAST:event_saveChangeBtnMouseClicked

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
       this.returnBack();
    }//GEN-LAST:event_homeBtnMouseClicked

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
       this.search();
    }//GEN-LAST:event_searchBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea clientAddressTxtarea;
    private javax.swing.JFormattedTextField clientFullNameTxtbx;
    private javax.swing.JFormattedTextField clientPhoneTxtbx;
    private javax.swing.JFormattedTextField clientUserNameTxtbx;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveChangeBtn;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables
    public void search(){
        if("".equals(this.clientUserNameTxtbx.getText())){
            MyMessageBox.displayMessage("Please input the client's username");
            this.disableAll();
        }else{
            clientUserName= this.clientUserNameTxtbx.getText().trim();
            this.clientToEdit= ClientController.getClient(clientUserName);
            if(clientToEdit==null){
                MyMessageBox.displayMessage("Client does not exist");
                this.disableAll();
            }else{
                
                this.enableAll();
            }
        }
    }
    public void saveChanges(){
        if(this.clientToEdit==null){
            MyMessageBox.displayMessage("Please input a correct user name");
        }else{
            if(this.areAllFieldsFilled()){
                this.clientToEdit.setClientAddress(this.clientAddressTxtarea.getText().trim());
                this.clientToEdit.setClientName(this.clientFullNameTxtbx.getText().trim());
                this.clientToEdit.setClientPhone(this.clientPhoneTxtbx.getText().trim());
                this.clientToEdit.setUserName(this.clientUserNameTxtbx.getText().trim());
                if(ClientController.updateClient(clientUserName,this.clientToEdit)){
                    MyMessageBox.displayMessage("Update Successfull");
                }
            }else{
                MyMessageBox.displayMessage("Operation unSuccessfull");
            }
        }
    }
    public boolean areAllFieldsFilled(){
        if(this.clientAddressTxtarea.getText()==""||"".equals(this.clientFullNameTxtbx.getText())||"".equals(this.clientPhoneTxtbx.getText())||this.clientUserNameTxtbx.getText()==""){
            MyMessageBox.displayMessage("All fields can not be left blank");
            return false;
        }
        return true;
    }
    public void enableAll(){
        this.clientAddressTxtarea.setEditable(true);
        this.clientFullNameTxtbx.setEditable(true);
        this.clientPhoneTxtbx.setEditable(true);
        this.clientAddressTxtarea.setText(this.clientToEdit.getClientAddress());
        this.clientFullNameTxtbx.setText(this.clientToEdit.getClientName());
        this.clientPhoneTxtbx.setText(this.clientToEdit.getClientPhone());
    }
    public void disableAll(){
         this.clientAddressTxtarea.setEditable(false);
        this.clientFullNameTxtbx.setEditable(false);
        this.clientPhoneTxtbx.setEditable(false);
        this.clientAddressTxtarea.setText("");
        this.clientFullNameTxtbx.setText("");
        this.clientPhoneTxtbx.setText("");
    }
     private void returnBack() {
        SalesOptionView salesPanel = new SalesOptionView(parentFrame);
        salesPanel.setGreeting(CurrentUser.userFullName.trim());
        this.transitToHomePage(salesPanel);
    }

    public void transitToHomePage(SalesOptionView sov) {
        this.setVisible(false);
        parentFrame.remove(this);
        sov.setSize(978, 570);
        parentFrame.add(sov);
        sov.setVisible(true);
     }
}
