/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.SalesView;

import Controller.LoginController;
import View.IGreetable;
import View.IHoverable;
import View.LoginView;
import View.PasswordChanger;
import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author user
 */
public class SalesOptionView extends javax.swing.JPanel implements IGreetable,IHoverable {

    /**
     * Creates new form OptionPanel
     */
    LoginView parentFrame;
    public SalesOptionView(LoginView ParentFrame) {
        initComponents();
        parentFrame=ParentFrame;
       
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        greeting = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        createSalesButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addClientButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        editClientButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        changePasswdBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 474));

        greeting.setFont(new java.awt.Font("BrowalliaUPC", 0, 24)); // NOI18N
        greeting.setForeground(new java.awt.Color(0, 165, 250));
        greeting.setText("Welcome");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        createSalesButton.setBackground(new java.awt.Color(183, 239, 240));
        createSalesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add records.jpg"))); // NOI18N
        createSalesButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        createSalesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createSalesButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createSalesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createSalesButtonMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 149, 0));
        jLabel1.setText("Add Sales Order");

        searchButton.setBackground(new java.awt.Color(183, 239, 240));
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ccc(s1).jpg"))); // NOI18N
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchButtonMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 149, 0));
        jLabel2.setText("Search");

        addClientButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Clientimager.jpg"))); // NOI18N
        addClientButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addClientButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addClientButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addClientButtonMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 149, 0));
        jLabel4.setText("Add client");

        logOutButton.setBackground(new java.awt.Color(183, 239, 240));
        logOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image logou.jpg"))); // NOI18N
        logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutButtonMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 149, 0));
        jLabel3.setText("Log Out");

        editClientButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        editClientButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editClientButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editClientButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editClientButtonMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 149, 0));
        jLabel5.setText("Edit Client Details");

        changePasswdBtn.setBackground(new java.awt.Color(183, 239, 240));
        changePasswdBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/secrecy-icon.png"))); // NOI18N
        changePasswdBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePasswdBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changePasswdBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changePasswdBtnMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 149, 0));
        jLabel7.setText("Change Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createSalesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(changePasswdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(logOutButton)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(changePasswdBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(createSalesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logOutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(editClientButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addClientButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3)
                        .addComponent(jLabel7)))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(greeting, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(greeting)
                .addGap(79, 79, 79)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
   
    //event handlers
    //<editor-fold defaultstate="collapsed">
    private void createSalesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createSalesButtonMouseEntered
       this.enter(this.createSalesButton);
    }//GEN-LAST:event_createSalesButtonMouseEntered

    private void createSalesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createSalesButtonMouseExited
       this.exit(this.createSalesButton);
    }//GEN-LAST:event_createSalesButtonMouseExited

    private void searchButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseEntered
       this.enter(this.searchButton);
    }//GEN-LAST:event_searchButtonMouseEntered

    private void searchButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseExited
       this.exit(this.searchButton);
    }//GEN-LAST:event_searchButtonMouseExited

    private void logOutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseEntered
        this.enter(this.logOutButton);
    }//GEN-LAST:event_logOutButtonMouseEntered

    private void logOutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseExited
       this.exit(this.logOutButton);
    }//GEN-LAST:event_logOutButtonMouseExited

    private void createSalesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createSalesButtonMouseClicked
       CreateSalesView salesCreator= new CreateSalesView(parentFrame);
       this.transitToCreateSales(salesCreator);
    }//GEN-LAST:event_createSalesButtonMouseClicked

    private void addClientButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addClientButtonMouseEntered
      this.enter(this.addClientButton);
    }//GEN-LAST:event_addClientButtonMouseEntered

    private void addClientButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addClientButtonMouseExited
       this.exit(this.addClientButton);
    }//GEN-LAST:event_addClientButtonMouseExited

    private void addClientButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addClientButtonMouseClicked
        CreateClientView clientCreator= new CreateClientView(parentFrame);
        this.transitToCreateClient(clientCreator);
    }//GEN-LAST:event_addClientButtonMouseClicked

    private void editClientButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editClientButtonMouseEntered
       this.enter(this.editClientButton);
    }//GEN-LAST:event_editClientButtonMouseEntered

    private void editClientButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editClientButtonMouseExited
       this.exit(this.editClientButton);
    }//GEN-LAST:event_editClientButtonMouseExited

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        SearchView searcher= new SearchView(parentFrame);
        this.transitToSearch(searcher);
    }//GEN-LAST:event_searchButtonMouseClicked

    private void editClientButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editClientButtonMouseClicked
        this.transitToEditClient(new EditClientView(parentFrame));
    }//GEN-LAST:event_editClientButtonMouseClicked

    private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseClicked
        this.logOut();
    }//GEN-LAST:event_logOutButtonMouseClicked

    private void changePasswdBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswdBtnMouseEntered
        this.enter(this.changePasswdBtn);
    }//GEN-LAST:event_changePasswdBtnMouseEntered

    private void changePasswdBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswdBtnMouseExited
        this.exit(this.changePasswdBtn);
    }//GEN-LAST:event_changePasswdBtnMouseExited

    private void changePasswdBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswdBtnMouseClicked
        this.transitToChangPasswordView(new PasswordChanger(parentFrame));
    }//GEN-LAST:event_changePasswdBtnMouseClicked
    //</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClientButton;
    private javax.swing.JButton changePasswdBtn;
    private javax.swing.JButton createSalesButton;
    private javax.swing.JButton editClientButton;
    private javax.swing.JLabel greeting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
    @Override
    public void setGreeting(String text){
        greeting.setText("Welcome "+text);
    }
    public void transitToCreateSales(CreateSalesView salesCreator){
       this.setVisible(false);
        parentFrame.remove(this);
        salesCreator.setSize(978, 570);
        parentFrame.add(salesCreator);
        salesCreator.setVisible(true);
    }
    public void transitToCreateClient(CreateClientView clientCreator ){
        this.setVisible(false);
        parentFrame.remove(this);
        clientCreator.setSize(978,570);
        parentFrame.add(clientCreator);
        clientCreator.setVisible(true);
    }
    public void transitToSearch(SearchView searcher){
         this.setVisible(false);
        parentFrame.remove(this);
        searcher.setSize(978,570);
        parentFrame.add(searcher);
        searcher.setVisible(true);
    }
     public void transitToEditClient(EditClientView clientEditor){
         this.setVisible(false);
        parentFrame.remove(this);
        clientEditor.setSize(978,570);
        parentFrame.add(clientEditor);
        clientEditor.setVisible(true);
    }
      public void transitToChangPasswordView(PasswordChanger pChange) {
        this.setVisible(false);
        parentFrame.remove(this);
        pChange.setSize(978, 570);
        parentFrame.add(pChange);
        pChange.setVisible(true);
    }
    public void logOut(){
        LoginView myView= new LoginView();
        this.setVisible(false);
        parentFrame.setVisible(false);
        myView.setVisible(true);
        myView.setLocationRelativeTo(null);
        LoginController.logOut();
    }

    @Override
    public void enter(JButton button) {
        button.setBackground(Color.orange);
        button.setSize((button.getWidth() + 15), (button.getHeight() + 15));
    }

    @Override
    public void exit(JButton button) {
        button.setBackground(new java.awt.Color(183, 239, 240));
        button.setSize((button.getWidth() - 15), (button.getHeight() - 15));
    }
}
