/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.SalesView;

import Controller.SalesController;
import Model.CurrentUser;
import Model.Sales;
import View.LoginView;
import View.MyMessageBox;

/**
 *
 * @author user
 */
public class SearchView extends javax.swing.JPanel {

    /**
     * Creates new form SearchView
     */
    LoginView parentFrame;
    Sales searchResult;
    public SearchView(LoginView parentFramer) {
        initComponents();
        this.errorMsg.setVisible(false);
        this.disableUserButtons();
        parentFrame=parentFramer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchTxtBx = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        errorMsg = new javax.swing.JLabel();
        salesIdTxt = new javax.swing.JLabel();
        viewRecBtn = new javax.swing.JButton();
        genInvoiceBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(72, 93, 215));
        jLabel1.setText("Search by Sales Id");

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ccc(s1).jpg"))); // NOI18N
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Results for Sales ID:");

        errorMsg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        errorMsg.setForeground(new java.awt.Color(204, 0, 0));
        errorMsg.setText("Sales Id does not exist");

        salesIdTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        salesIdTxt.setForeground(new java.awt.Color(0, 102, 102));
        salesIdTxt.setText("salesId");

        viewRecBtn.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        viewRecBtn.setForeground(new java.awt.Color(0, 165, 250));
        viewRecBtn.setText("View Record");
        viewRecBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewRecBtnMouseClicked(evt);
            }
        });

        genInvoiceBtn.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        genInvoiceBtn.setForeground(new java.awt.Color(0, 165, 250));
        genInvoiceBtn.setText("Generate Invoice");
        genInvoiceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genInvoiceBtnMouseClicked(evt);
            }
        });

        homeBtn.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(65, 104, 197));
        homeBtn.setText("Home");
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(searchBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addComponent(salesIdTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(searchTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errorMsg))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(viewRecBtn)
                        .addGap(107, 107, 107)
                        .addComponent(genInvoiceBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorMsg))
                .addGap(29, 29, 29)
                .addComponent(searchBtn)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(salesIdTxt))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewRecBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(genInvoiceBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        this.returnBack();
    }//GEN-LAST:event_homeBtnMouseClicked

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        int salesId=0;
        try{
            salesId= Integer.valueOf(this.searchTxtBx.getText().trim());
        }catch(NumberFormatException ex){
            MyMessageBox.displayMessage("Please Enter a Number as the sales Id");
        }
        this.search(salesId);
    }//GEN-LAST:event_searchBtnMouseClicked

    private void viewRecBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRecBtnMouseClicked
        this.transitToSalesViewer();
    }//GEN-LAST:event_viewRecBtnMouseClicked

    private void genInvoiceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genInvoiceBtnMouseClicked
       this.transitToInvoiceGenerator();
    }//GEN-LAST:event_genInvoiceBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorMsg;
    private javax.swing.JButton genInvoiceBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel salesIdTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxtBx;
    private javax.swing.JButton viewRecBtn;
    // End of variables declaration//GEN-END:variables
    public void search(int salesId){
        this.searchResult= SalesController.getSales(salesId);
        if(searchResult==null){
            this.disableUserButtons();
            this.errorMsg.setVisible(true);
            this.salesIdTxt.setText("");
        }else{
            this.enableUserButtons();
            this.errorMsg.setVisible(false);
            this.salesIdTxt.setText(String.valueOf(this.searchResult.getSalesId()));
        }
    }
    private void disableUserButtons(){
        this.viewRecBtn.setEnabled(false);
        this.genInvoiceBtn.setEnabled(false);
    }
    public void enableUserButtons(){
        this.viewRecBtn.setEnabled(true);
        this.genInvoiceBtn.setEnabled(true);
    }
    private void returnBack() {
        SalesOptionView salesPanel = new SalesOptionView(parentFrame);
        salesPanel.setGreeting(CurrentUser.userFullName.trim());
        this.transitToHomePage(salesPanel);
    }

    public void transitToHomePage(SalesOptionView sov) {
        this.setVisible(false);
        parentFrame.remove(this);
        sov.setSize(978, 570);
        parentFrame.add(sov);
        sov.setVisible(true);

    }
    public void transitToSalesViewer(){
        SalesViewer salesView=new SalesViewer(this.searchResult,this.parentFrame);
        this.setVisible(false);
        parentFrame.remove(this);
        salesView.setSize(978,570);
        parentFrame.add(salesView);
        salesView.setVisible(true);
    }
    public void transitToInvoiceGenerator(){
        InvoiceGenerator iGenerator= new InvoiceGenerator(this.searchResult,this.parentFrame);
        this.setVisible(false);
        parentFrame.remove(this);
        iGenerator.setSize(978,570);
        parentFrame.add(iGenerator);
        iGenerator.setVisible(true);
    }

}
